import type { VietnameseMeetingNotes } from "./gemini";

export type ExportTemplateId =
  | "standard"
  | "notion"
  | "slack"
  | "email"
  | "zalo"
  | "googledocs";

export type ExportTemplate = {
  id: ExportTemplateId;
  label: string;
  description: string;
  icon: string;
  format: (notes: VietnameseMeetingNotes) => string;
};

export const EXPORT_TEMPLATES: ExportTemplate[] = [
  {
    id: "standard",
    label: "Standard Markdown",
    description: "Format mặc định — đầy đủ, có bảng, có transcript",
    icon: "📄",
    format: formatStandard,
  },
  {
    id: "notion",
    label: "Notion",
    description: "Tương thích Notion — callout blocks, toggle sections",
    icon: "📓",
    format: formatNotion,
  },
  {
    id: "slack",
    label: "Slack / Teams",
    description: "Tin nhắn gọn — paste vào Slack/Teams được ngay",
    icon: "💬",
    format: formatSlack,
  },
  {
    id: "email",
    label: "Email",
    description: "HTML email-ready — gửi cho team/client",
    icon: "📧",
    format: formatEmail,
  },
  {
    id: "zalo",
    label: "Zalo / Chat",
    description: "Text thuần — paste vào Zalo, Messenger, WhatsApp",
    icon: "📱",
    format: formatZalo,
  },
  {
    id: "googledocs",
    label: "Google Docs",
    description: "Format cho Google Docs — headings, bullets, tables",
    icon: "📝",
    format: formatGoogleDocs,
  },
];

function formatStandard(notes: VietnameseMeetingNotes): string {
  const lines = [
    "# Meeting Notes",
    "",
    "## 1. Tóm tắt điều hành",
    ...formatBulletList(notes.executiveSummary),
    "",
    "## 2. Thông tin cuộc họp",
    `- Ngôn ngữ: ${safeText(notes.meetingOverview.language)}`,
    `- Thời lượng: ${safeText(notes.meetingOverview.duration)}`,
    `- Số người nói: ${String(notes.meetingOverview.speakerCount ?? "Chưa xác định")}`,
    `- Chủ đề chính: ${safeText(notes.meetingOverview.mainTopic)}`,
    "",
    "## 3. Nội dung chính",
    ...formatDiscussionPoints(notes.keyDiscussionPoints),
    "",
    "## 4. Quyết định",
    ...formatBulletList(notes.decisions),
    "",
    "## 5. Action Items",
    "| Việc cần làm | Người phụ trách | Deadline | Ưu tiên | Ghi chú |",
    "|---|---|---|---|---|",
    ...formatActionItemsTable(notes.actionItems),
    "",
    "## 6. Rủi ro / Blockers",
    ...formatBulletList(notes.risksAndBlockers),
    "",
    "## 7. Câu hỏi còn mở",
    ...formatBulletList(notes.openQuestions),
  ];

  return lines.join("\n");
}

function formatNotion(notes: VietnameseMeetingNotes): string {
  const lines = [
    `# ${notes.title || "Meeting Notes"}`,
    "",
    "> 📋 Meeting notes generated by cuochop",
    "",
    "## 📌 Tóm tắt",
    "",
    ...notes.executiveSummary.map((s: string) => `- ${s}`),
    "",
    "<details>",
    "<summary><b>📊 Thông tin cuộc họp</b></summary>",
    "",
    `| Thông tin | Giá trị |`,
    `|---|---|`,
    `| Thời lượng | ${safeText(notes.meetingOverview.duration)} |`,
    `| Số người nói | ${String(notes.meetingOverview.speakerCount ?? "N/A")} |`,
    `| Chủ đề | ${safeText(notes.meetingOverview.mainTopic)} |`,
    "",
    "</details>",
    "",
    "## ✅ Quyết định đã chốt",
    "",
    ...notes.decisions.map((d: string) => `- [x] ${d}`),
    "",
    "## 🎯 Action Items",
    "",
    ...notes.actionItems.map((item: { task: string; owner: string; deadline: string; priority: string }) => {
      const priority = item.priority === "High" ? "🔴" : item.priority === "Medium" ? "🟡" : "🟢";
      return `- [ ] ${priority} **${safeText(item.task)}** — @${safeText(item.owner)} — ${safeText(item.deadline)}`;
    }),
    "",
    "## ⚠️ Risks & Blockers",
    "",
    ...notes.risksAndBlockers.map((r: string) => `- ⚠️ ${r}`),
    "",
    "## ❓ Open Questions",
    "",
    ...notes.openQuestions.map((q: string) => `- ❓ ${q}`),
    "",
    "---",
    `*Generated: ${new Date().toLocaleDateString("vi-VN")}*`,
  ];

  return lines.join("\n");
}

function formatSlack(notes: VietnameseMeetingNotes): string {
  const lines = [
    `:clipboard: *${notes.title || "Meeting Notes"}*`,
    "",
    ":star: *Tóm tắt:*",
    ...notes.executiveSummary.map((s: string) => `  • ${s}`),
    "",
    ":white_check_mark: *Quyết định:*",
    ...notes.decisions.map((d: string) => `  • ${d}`),
    "",
    ":dart: *Action Items:*",
    ...notes.actionItems.map((item: { task: string; owner: string; deadline: string; priority: string }) => {
      const priority = item.priority === "High" ? ":red_circle:" : item.priority === "Medium" ? ":yellow_circle:" : ":green_circle:";
      return `  ${priority} *${safeText(item.task)}* — ${safeText(item.owner)} — ${safeText(item.deadline)}`;
    }),
  ];

  if (notes.risksAndBlockers.length > 0) {
    lines.push("", ":warning: *Blockers:*");
    notes.risksAndBlockers.forEach((r: string) => lines.push(`  • ${r}`));
  }

  if (notes.openQuestions.length > 0) {
    lines.push("", ":question: *Câu hỏi còn mở:*");
    notes.openQuestions.forEach((q: string) => lines.push(`  • ${q}`));
  }

  return lines.join("\n");
}

function formatEmail(notes: VietnameseMeetingNotes): string {
  const actionRows = notes.actionItems
    .map((item: { task: string; owner: string; deadline: string; priority: string }) => {
      const priorityColor = item.priority === "High" ? "#ef4444" : item.priority === "Medium" ? "#f59e0b" : "#22c55e";
      return `<tr>
        <td style="padding:8px;border:1px solid #e5e7eb;">${escapeHtml(item.task)}</td>
        <td style="padding:8px;border:1px solid #e5e7eb;">${escapeHtml(item.owner)}</td>
        <td style="padding:8px;border:1px solid #e5e7eb;">${escapeHtml(item.deadline)}</td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">
          <span style="background:${priorityColor};color:white;padding:2px 8px;border-radius:12px;font-size:12px;">
            ${escapeHtml(item.priority)}
          </span>
        </td>
      </tr>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:20px;color:#1f2937;">
  <h1 style="color:#111827;border-bottom:2px solid #3b82f6;padding-bottom:8px;">
    ${escapeHtml(notes.title || "Meeting Notes")}
  </h1>

  <h2 style="color:#3b82f6;">📌 Tóm tắt</h2>
  <ul>${notes.executiveSummary.map((s: string) => `<li>${escapeHtml(s)}</li>`).join("")}</ul>

  <h2 style="color:#3b82f6;">✅ Quyết định</h2>
  <ul>${notes.decisions.map((d: string) => `<li>${escapeHtml(d)}</li>`).join("")}</ul>

  <h2 style="color:#3b82f6;">🎯 Action Items</h2>
  <table style="width:100%;border-collapse:collapse;margin:12px 0;">
    <thead>
      <tr style="background:#f3f4f6;">
        <th style="padding:8px;border:1px solid #e5e7eb;text-align:left;">Task</th>
        <th style="padding:8px;border:1px solid #e5e7eb;text-align:left;">Owner</th>
        <th style="padding:8px;border:1px solid #e5e7eb;text-align:left;">Deadline</th>
        <th style="padding:8px;border:1px solid #e5e7eb;text-align:center;">Priority</th>
      </tr>
    </thead>
    <tbody>${actionRows}</tbody>
  </table>

  ${notes.risksAndBlockers.length > 0 ? `
  <h2 style="color:#ef4444;">⚠️ Blockers</h2>
  <ul>${notes.risksAndBlockers.map((r: string) => `<li>${escapeHtml(r)}</li>`).join("")}</ul>
  ` : ""}

  ${notes.openQuestions.length > 0 ? `
  <h2 style="color:#f59e0b;">❓ Câu hỏi còn mở</h2>
  <ul>${notes.openQuestions.map((q: string) => `<li>${escapeHtml(q)}</li>`).join("")}</ul>
  ` : ""}

  <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
  <p style="color:#9ca3af;font-size:12px;">
    Generated by cuochop — ${new Date().toLocaleDateString("vi-VN")}
  </p>
</body>
</html>`;
}

function formatZalo(notes: VietnameseMeetingNotes): string {
  const lines: string[] = [];

  lines.push(`📋 ${notes.title || "Meeting Notes"}`);
  lines.push("");

  lines.push("📌 TÓM TẮT:");
  notes.executiveSummary.forEach((s: string) => lines.push(`• ${s}`));
  lines.push("");

  if (notes.decisions.length > 0) {
    lines.push("✅ QUYẾT ĐỊNH:");
    notes.decisions.forEach((d: string) => lines.push(`• ${d}`));
    lines.push("");
  }

  if (notes.actionItems.length > 0) {
    lines.push("🎯 ACTION ITEMS:");
    notes.actionItems.forEach((item: { task: string; owner: string; deadline: string; priority: string }) => {
      const icon = item.priority === "High" ? "🔴" : item.priority === "Medium" ? "🟡" : "🟢";
      lines.push(`${icon} ${item.task}`);
      lines.push(`   👤 ${item.owner} / ⏰ ${item.deadline}`);
    });
    lines.push("");
  }

  if (notes.risksAndBlockers.length > 0) {
    lines.push("⚠️ BLOCKERS:");
    notes.risksAndBlockers.forEach((r: string) => lines.push(`• ${r}`));
    lines.push("");
  }

  if (notes.openQuestions.length > 0) {
    lines.push("❓ CÂU HỎI CÒN MỞ:");
    notes.openQuestions.forEach((q: string) => lines.push(`• ${q}`));
  }

  return lines.join("\n");
}

function formatGoogleDocs(notes: VietnameseMeetingNotes): string {
  const lines = [
    notes.title || "Meeting Notes",
    "",
    "TÓM TẮT ĐIỀU HÀNH",
    "",
    ...notes.executiveSummary.map((s: string) => `• ${s}`),
    "",
    "THÔNG TIN CUỘC HỌP",
    "",
    `Ngôn ngữ: ${safeText(notes.meetingOverview.language)}`,
    `Thời lượng: ${safeText(notes.meetingOverview.duration)}`,
    `Số người nói: ${String(notes.meetingOverview.speakerCount ?? "N/A")}`,
    `Chủ đề chính: ${safeText(notes.meetingOverview.mainTopic)}`,
    "",
    "NỘI DUNG CHÍNH",
    "",
    ...formatDiscussionPointsSimple(notes.keyDiscussionPoints),
    "",
    "QUYẾT ĐỊNH",
    "",
    ...notes.decisions.map((d: string, i: number) => `${i + 1}. ${d}`),
    "",
    "ACTION ITEMS",
    "",
    ...notes.actionItems.map((item: { task: string; owner: string; deadline: string; priority: string; notes: string }, i: number) => {
      return [
        `${i + 1}. ${safeText(item.task)}`,
        `   Người phụ trách: ${safeText(item.owner)}`,
        `   Deadline: ${safeText(item.deadline)}`,
        `   Ưu tiên: ${safeText(item.priority)}`,
        item.notes ? `   Ghi chú: ${item.notes}` : "",
      ].filter(Boolean).join("\n");
    }),
    "",
    "RỦI RO / BLOCKERS",
    "",
    ...notes.risksAndBlockers.map((r: string) => `• ${r}`),
    "",
    "CÂU HỎI CÒN MỞ",
    "",
    ...notes.openQuestions.map((q: string) => `• ${q}`),
  ];

  return lines.join("\n");
}

// Helpers
function formatBulletList(items: string[] | undefined): string[] {
  const values = items?.filter((s: string) => s.trim().length > 0) ?? [];
  return values.length > 0 ? values.map((s: string) => `- ${s}`) : ["- Chưa xác định"];
}

function formatDiscussionPoints(points: VietnameseMeetingNotes["keyDiscussionPoints"]): string[] {
  if (!points || points.length === 0) return ["### Chưa xác định", "- Chưa xác định"];
  return points.flatMap((p: { title: string; details: string[] }, i: number) => [
    `### 3.${i + 1} ${safeText(p.title)}`,
    ...formatBulletList(p.details),
  ]);
}

function formatDiscussionPointsSimple(points: VietnameseMeetingNotes["keyDiscussionPoints"]): string[] {
  if (!points || points.length === 0) return ["Chưa xác định"];
  return points.flatMap((p: { title: string; details: string[] }) => [
    `${safeText(p.title)}`,
    ...(p.details ?? []).map((d: string) => `  • ${d}`),
  ]);
}

function formatActionItemsTable(items: VietnameseMeetingNotes["actionItems"]): string[] {
  if (!items || items.length === 0) return ["| Chưa xác định | Chưa xác định | Chưa xác định | Chưa xác định | Chưa xác định |"];
  return items.map(
    (item: { task: string; owner: string; deadline: string; priority: string; notes: string }) =>
      `| ${tableText(item.task)} | ${tableText(item.owner)} | ${tableText(item.deadline)} | ${tableText(item.priority)} | ${tableText(item.notes)} |`,
  );
}

function safeText(value: unknown): string {
  return typeof value === "string" && value.length > 0 ? value : "Chưa xác định";
}

function tableText(value: unknown): string {
  return safeText(value).replaceAll("|", "\\|");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function getExportTemplate(id: string): ExportTemplate {
  return EXPORT_TEMPLATES.find((t) => t.id === id) ?? EXPORT_TEMPLATES[0];
}
